twitch: riotgames        # Twitch канал
music: false             # Включить фоновую музыку
colored: true            # Включить цветные сообщения
music-name: pokemon.mp3  # Файл фоновой музыки
team-size: 2             # Размер команды
team-num: 3              # Количество команд
names: [Пикачу, Иви, Сильвеон, Бульбазавр, Амбреон, Райчу, Пичу, Чаризард, Мьюту, Эспеон, Сквиртл, Деденне, Шеймин, Лифеон, Хупа, Ивельтал, Чармандер, Грениндзя, Зубат, Парас] # Имя бойцов
team-names: [Первая команда, Вторая команда, Третья команда, Четвёртая команда, Пятая команда, Шестая команда, Седьмая команда, Восьмая команда, Девятая команда, Десятая команда] # Имя команд
fighter:                 # Характеристики бойцов
  hp:                    # Очки здоровья
    min: 100
    max: 120
  power:                 # Сила атаки
    min: 15
    max: 25
  critical-chance:       # Шанс критического удара
    min: 0
    max: 0.2
  critical-multiplier:   # Множитель критического урона
    min: 1.5
    max: 2
  accuracy:              # Меткость
    min: 0.8
    max: 1.0
  damage-deviation: 0.15 # Отклонение урона
arena:                   # Характеристики арены
  hp-multiplier:         # Множитель очков здоровья
    min: 5
    max: 10
  power-multiplier:      # Множитель силы атаки
    min: 8
    max: 12
  double-hit-chance:     # Шанс двойного урона
    min: 0
    max: 0.6
